config/routes.rb
Rails.application.routes.draw do
  resources :videos
  get 'pages/about'

  get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code4Uwe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	
	<!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	
  </head>
  <body>
  
	  <nav>
		<div class="nav-wrapper">
			<a href="#!" class="brand-logo">Code4Uwe</a>
			<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
			<ul class="right hide-on-med-and-down">
				<li><a href="#"><i class="material-icons">view_list</i></a></li>
				<li><a href="<%= pages_about_path %>"><i class="material-icons">perm_identity</i></a></li>
				<li><a href="<%= pages_contact_path %>"><i class="i class="material-icons">room</i></a></li>
			>/ul>
			<ul class="side-nav" id="mobile-demo">
				<li><a href="#"><i class="material-icons">view_list</i></a></li>
				<li><a href="<%= pages_about_path %>"><i class="material-icons">perm_identity</i></a></li>
				<li><a href="<%= pages_contact_path %>"><i class="i class="material-icons">room</i></a></li>
			>/ul>
		>/div>
	</nav>
	
	<div class="row">
		<div class="col m10 offset-m1">
			<%= yield %>
		</div>
	</div>
	
	<script>
		$(".button-collapse").sideNav();
	</script>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h3>Contact</h3>

<div class="card z-depth-3">
	<div class="card-content"> 
		<p>Find me here</p>
	</div>
</div>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.text_field :wistia, :placeholder => 'Link', :length => '10' %>
  </div>

  <div class="input-field">
    <%= form.text_area :description, :placeholder => 'Link', :length => '800', :class ==> 'materialize-textarea' %>
  </div>
  <div class="input-field">
    <%= form.text_area :author, :placeholder => 'Link', :length => '20' 
  </div>
  <button class="btn waves-effect waves light" type="submit" name="action">Submit</button>
  <a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Back</a>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form' %>
	</div>
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Wistia</th>
      <th>Description</th>
	  <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.wistia %></td>
        <td><%= video.description %></td>
		<td><%= video.author %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<div class="card">
	<div class="card-content">
		<%= render 'form' %>
	</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wistia:</strong>
  <%= @video.wistia %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>